<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.3.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['_2Checkout.name'] = "2Checkout
";
$lang['_2Checkout.vendor_id'] = "Vendor";
$lang['_2Checkout.secret_word'] = "Secret Word
";
$lang['_2Checkout.api_username'] = "API ime
";
$lang['_2Checkout.api_username_note'] = "Ovaj, kao i API lozinku, su potrebne kako bi se obradi povrat kroz 2Checkout.

";
$lang['_2Checkout.api_password'] = "API Lozinka
";
$lang['_2Checkout.test_mode'] = "Test Mode
";
$lang['2Checkout.refund.comment'] = "Pokretanje povrat za %1\$s.
"; // %1$s is the refund amount
$lang['_2Checkout.buildprocess.submit'] = "Plati sa 2Checkout
";
$lang['_2Checkout.!error.vendor_id.empty'] = "Unesite svoj Vendor Broj računa.
";
$lang['_2Checkout.!error.secret_word.empty'] = "Unesite svoju tajnu Word.
";
$lang['_2Checkout.!error.test_mode.valid'] = "Test mod mora biti postavljen na bilo 'pravi' ili 'lažne'.
";
$lang['_2Checkout.!error.key.valid'] = "Ključ se koristi da biste potvrdili ove prodaje nastao iz 2Checkout je nevažeći.
";
$lang['_2Checkout.!error.credit_card_processed.completed'] = "Transakcija nije uspješno obra.
";
$lang['_2Checkout.!error.sid.valid'] = "The Number Vendor račun ne podudara s brojem računa koje transakcije.
";
?>